[book]
title = "Parlar Veneto"
authors = ["Josh"]
description = "A Practical Grammar of the Venetian Language"
language = "en"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/joshrotenberg/parlar-veneto"
edit-url-template = "https://github.com/joshrotenberg/parlar-veneto/edit/main/{path}"

[output.html.fold]
enable = true
level = 1
